// Package features defines the point-in-time feature extractor for learned
// strategies. Features are defined once here, in Go, and the training data
// is generated by running production code over history — no second
// implementation in Python.
//
// The Extractor is deterministic and pure: same View and event → same vector.
// View exposes only as-of-now state — no database access, no future leakage.
// Point-in-time correctness is enforced by the type system.
package features

import (
	"crypto/sha256"
	"encoding/hex"
	"sort"
	"strconv"

	"github.com/LordFarquaadtheCreator/kalshi-ghost-trader/v2/internal/domain/match"
	"github.com/LordFarquaadtheCreator/kalshi-ghost-trader/v2/internal/domain/strategy"
)

// View is the point-in-time state the extractor sees. It contains only
// as-of-now information — no access to the database, no future data.
// This is the type-level enforcement of point-in-time correctness.
type View struct {
	// Score state
	SetsHome      int
	SetsAway      int
	GamesHome     int
	GamesAway     int
	HomePoints    int
	AwayPoints    int
	Server        int // 1=home, 2=away
	IsTiebreak    bool
	SetNumber     int
	GameNumber    int
	PointNumber   int
	IsBreakPoint  bool
	IsSetPoint    bool
	IsMatchPoint  bool

	// Market microstructure
	PriceCents    int   // current price of the market we're considering
	BestBidCents  int   // top-of-book bid
	BestAskCents  int   // top-of-book ask
	BestBidSize   int   // displayed size at best bid
	BestAskSize   int   // displayed size at best ask
	Volume        int   // total volume
	PriceTS       int64 // timestamp of last price update

	// Derived pricing
	MarkovFairValueCents int // from the Markov model
	MarkovDeltaCents     int // fair value change since last point

	// Match context
	Series        string // ATP/WTA/ITF/Challenger
	IsDoubles     bool
	BestOf        int    // 3 or 5
	ElapsedMS     int64  // time since match start

	// Player context
	PreMatchImpliedPriceCents int // opening price
	RankDifferential          int // positive = home favored

	// Session
	PointsSincePriceMove int
	SeqGapIndicator      int // 0=none, 1=gap detected
}

// Extractor is deterministic and pure: same View and event → same vector.
type Extractor interface {
	Names() []string          // stable, ordered; hashed into feature_hash
	Extract(v View, ev match.Event) []float64
}

// DefaultExtractor implements the A.3 feature set.
type DefaultExtractor struct {
	names []string
}

// NewDefaultExtractor creates the standard feature extractor.
func NewDefaultExtractor() *DefaultExtractor {
	return &DefaultExtractor{
		names: defaultFeatureNames(),
	}
}

// Names returns the stable, ordered feature names.
func (e *DefaultExtractor) Names() []string {
	out := make([]string, len(e.names))
	copy(out, e.names)
	return out
}

// Extract produces the feature vector from a View and event.
func (e *DefaultExtractor) Extract(v View, ev match.Event) []float64 {
	vec := make([]float64, len(e.names))
	for i, name := range e.names {
		vec[i] = extractFeature(name, v, ev)
	}
	return vec
}

// FeatureHash returns a stable hash of the feature-name list.
// The hash ensures that a model trained with one feature set is not
// served with a different one.
func FeatureHash(names []string) string {
	sorted := make([]string, len(names))
	copy(sorted, names)
	sort.Strings(sorted)

	h := sha256.New()
	for _, n := range sorted {
		h.Write([]byte(n))
		h.Write([]byte{0}) // null separator
	}
	return hex.EncodeToString(h.Sum(nil))[:16]
}

// Hash returns the feature hash for this extractor.
func (e *DefaultExtractor) Hash() string {
	return FeatureHash(e.names)
}

// defaultFeatureNames returns the ordered feature names from the A.3 table.
func defaultFeatureNames() []string {
	return []string{
		// Score state
		"sets_home",
		"sets_away",
		"games_home",
		"games_away",
		"home_points",
		"away_points",
		"server",
		"is_tiebreak",
		"set_number",
		"game_number",
		"point_number",
		"is_break_point",
		"is_set_point",
		"is_match_point",

		// Derived pricing
		"markov_fair_value_cents",
		"edge_cents", // fair_value - price
		"markov_delta_cents",

		// Market microstructure
		"spread_cents",
		"best_bid_size",
		"best_ask_size",
		"imbalance", // (bid_size - ask_size) / (bid_size + ask_size)
		"volume",
		"price_velocity_10s",
		"price_velocity_60s",

		// Match context
		"series_atp",
		"series_wta",
		"series_itf",
		"series_challenger",
		"is_doubles",
		"best_of",
		"elapsed_minutes",

		// Player context
		"pre_match_implied_price_cents",
		"rank_differential",

		// Session
		"points_since_price_move",
		"seq_gap_indicator",
	}
}

// extractFeature extracts a single feature by name.
func extractFeature(name string, v View, ev match.Event) float64 {
	switch name {
	// Score state
	case "sets_home":
		return float64(v.SetsHome)
	case "sets_away":
		return float64(v.SetsAway)
	case "games_home":
		return float64(v.GamesHome)
	case "games_away":
		return float64(v.GamesAway)
	case "home_points":
		return float64(v.HomePoints)
	case "away_points":
		return float64(v.AwayPoints)
	case "server":
		return float64(v.Server)
	case "is_tiebreak":
		return boolToFloat(v.IsTiebreak)
	case "set_number":
		return float64(v.SetNumber)
	case "game_number":
		return float64(v.GameNumber)
	case "point_number":
		return float64(v.PointNumber)
	case "is_break_point":
		return boolToFloat(v.IsBreakPoint)
	case "is_set_point":
		return boolToFloat(v.IsSetPoint)
	case "is_match_point":
		return boolToFloat(v.IsMatchPoint)

	// Derived pricing
	case "markov_fair_value_cents":
		return float64(v.MarkovFairValueCents)
	case "edge_cents":
		return float64(v.MarkovFairValueCents - v.PriceCents)
	case "markov_delta_cents":
		return float64(v.MarkovDeltaCents)

	// Market microstructure
	case "spread_cents":
		return float64(v.BestAskCents - v.BestBidCents)
	case "best_bid_size":
		return float64(v.BestBidSize)
	case "best_ask_size":
		return float64(v.BestAskSize)
	case "imbalance":
		total := v.BestBidSize + v.BestAskSize
		if total == 0 {
			return 0
		}
		return float64(v.BestBidSize-v.BestAskSize) / float64(total)
	case "volume":
		return float64(v.Volume)
	case "price_velocity_10s":
		// Simplified: would need rolling window from the loop.
		return 0
	case "price_velocity_60s":
		return 0

	// Match context
	case "series_atp":
		return boolToFloat(v.Series == "ATP")
	case "series_wta":
		return boolToFloat(v.Series == "WTA")
	case "series_itf":
		return boolToFloat(v.Series == "ITF")
	case "series_challenger":
		return boolToFloat(v.Series == "Challenger")
	case "is_doubles":
		return boolToFloat(v.IsDoubles)
	case "best_of":
		return float64(v.BestOf)
	case "elapsed_minutes":
		return float64(v.ElapsedMS) / 60000.0

	// Player context
	case "pre_match_implied_price_cents":
		return float64(v.PreMatchImpliedPriceCents)
	case "rank_differential":
		return float64(v.RankDifferential)

	// Session
	case "points_since_price_move":
		return float64(v.PointsSincePriceMove)
	case "seq_gap_indicator":
		return float64(v.SeqGapIndicator)

	default:
		return 0
	}
}

func boolToFloat(b bool) float64 {
	if b {
		return 1.0
	}
	return 0.0
}

// ViewFromMatchView converts a strategy.MatchView to a features.View.
// This is the bridge between the loop's state and the feature extractor.
func ViewFromMatchView(mv strategy.MatchView, marketTicker string) View {
	price := mv.Prices[marketTicker]
	ts := mv.PriceTS[marketTicker]

	homePoints, _ := strconv.Atoi(mv.HomePoints)
	awayPoints, _ := strconv.Atoi(mv.AwayPoints)

	return View{
		SetsHome:     mv.SetsHome,
		SetsAway:     mv.SetsAway,
		GamesHome:    mv.GamesHome,
		GamesAway:    mv.GamesAway,
		HomePoints:   homePoints,
		AwayPoints:   awayPoints,
		Server:       mv.Server,
		IsTiebreak:   mv.IsTiebreak,
		SetNumber:    mv.SetNumber,
		GameNumber:   mv.GameNumber,
		PointNumber:  mv.PointNumber,
		IsBreakPoint: mv.IsBreakPoint,
		IsSetPoint:   mv.IsSetPoint,
		IsMatchPoint: mv.IsMatchPoint,
		PriceCents:   price,
		PriceTS:      ts,
	}
}
